function InitGlobals()
end

function InitCustomPlayerSlots()
    SetPlayerStartLocation(Player(0), 0)
    ForcePlayerStartLocation(Player(0), 0)
    SetPlayerColor(Player(0), ConvertPlayerColor(0))
    SetPlayerRacePreference(Player(0), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(0), true)
    SetPlayerController(Player(0), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(1), 1)
    ForcePlayerStartLocation(Player(1), 1)
    SetPlayerColor(Player(1), ConvertPlayerColor(1))
    SetPlayerRacePreference(Player(1), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(1), true)
    SetPlayerController(Player(1), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(2), 2)
    ForcePlayerStartLocation(Player(2), 2)
    SetPlayerColor(Player(2), ConvertPlayerColor(2))
    SetPlayerRacePreference(Player(2), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(2), true)
    SetPlayerController(Player(2), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(3), 3)
    ForcePlayerStartLocation(Player(3), 3)
    SetPlayerColor(Player(3), ConvertPlayerColor(3))
    SetPlayerRacePreference(Player(3), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(3), true)
    SetPlayerController(Player(3), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(4), 4)
    ForcePlayerStartLocation(Player(4), 4)
    SetPlayerColor(Player(4), ConvertPlayerColor(4))
    SetPlayerRacePreference(Player(4), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(4), true)
    SetPlayerController(Player(4), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(5), 5)
    ForcePlayerStartLocation(Player(5), 5)
    SetPlayerColor(Player(5), ConvertPlayerColor(5))
    SetPlayerRacePreference(Player(5), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(5), true)
    SetPlayerController(Player(5), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(6), 6)
    ForcePlayerStartLocation(Player(6), 6)
    SetPlayerColor(Player(6), ConvertPlayerColor(6))
    SetPlayerRacePreference(Player(6), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(6), true)
    SetPlayerController(Player(6), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(7), 7)
    ForcePlayerStartLocation(Player(7), 7)
    SetPlayerColor(Player(7), ConvertPlayerColor(7))
    SetPlayerRacePreference(Player(7), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(7), true)
    SetPlayerController(Player(7), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(8), 8)
    ForcePlayerStartLocation(Player(8), 8)
    SetPlayerColor(Player(8), ConvertPlayerColor(8))
    SetPlayerRacePreference(Player(8), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(8), true)
    SetPlayerController(Player(8), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(9), 9)
    ForcePlayerStartLocation(Player(9), 9)
    SetPlayerColor(Player(9), ConvertPlayerColor(9))
    SetPlayerRacePreference(Player(9), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(9), true)
    SetPlayerController(Player(9), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(10), 10)
    ForcePlayerStartLocation(Player(10), 10)
    SetPlayerColor(Player(10), ConvertPlayerColor(10))
    SetPlayerRacePreference(Player(10), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(10), true)
    SetPlayerController(Player(10), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(11), 11)
    ForcePlayerStartLocation(Player(11), 11)
    SetPlayerColor(Player(11), ConvertPlayerColor(11))
    SetPlayerRacePreference(Player(11), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(11), true)
    SetPlayerController(Player(11), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(12), 12)
    ForcePlayerStartLocation(Player(12), 12)
    SetPlayerColor(Player(12), ConvertPlayerColor(12))
    SetPlayerRacePreference(Player(12), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(12), true)
    SetPlayerController(Player(12), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(13), 13)
    ForcePlayerStartLocation(Player(13), 13)
    SetPlayerColor(Player(13), ConvertPlayerColor(13))
    SetPlayerRacePreference(Player(13), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(13), true)
    SetPlayerController(Player(13), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(14), 14)
    ForcePlayerStartLocation(Player(14), 14)
    SetPlayerColor(Player(14), ConvertPlayerColor(14))
    SetPlayerRacePreference(Player(14), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(14), true)
    SetPlayerController(Player(14), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(15), 15)
    ForcePlayerStartLocation(Player(15), 15)
    SetPlayerColor(Player(15), ConvertPlayerColor(15))
    SetPlayerRacePreference(Player(15), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(15), true)
    SetPlayerController(Player(15), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(16), 16)
    ForcePlayerStartLocation(Player(16), 16)
    SetPlayerColor(Player(16), ConvertPlayerColor(16))
    SetPlayerRacePreference(Player(16), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(16), true)
    SetPlayerController(Player(16), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(17), 17)
    ForcePlayerStartLocation(Player(17), 17)
    SetPlayerColor(Player(17), ConvertPlayerColor(17))
    SetPlayerRacePreference(Player(17), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(17), true)
    SetPlayerController(Player(17), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(18), 18)
    ForcePlayerStartLocation(Player(18), 18)
    SetPlayerColor(Player(18), ConvertPlayerColor(18))
    SetPlayerRacePreference(Player(18), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(18), true)
    SetPlayerController(Player(18), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(19), 19)
    ForcePlayerStartLocation(Player(19), 19)
    SetPlayerColor(Player(19), ConvertPlayerColor(19))
    SetPlayerRacePreference(Player(19), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(19), true)
    SetPlayerController(Player(19), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(20), 20)
    ForcePlayerStartLocation(Player(20), 20)
    SetPlayerColor(Player(20), ConvertPlayerColor(20))
    SetPlayerRacePreference(Player(20), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(20), true)
    SetPlayerController(Player(20), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(21), 21)
    ForcePlayerStartLocation(Player(21), 21)
    SetPlayerColor(Player(21), ConvertPlayerColor(21))
    SetPlayerRacePreference(Player(21), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(21), true)
    SetPlayerController(Player(21), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(22), 22)
    ForcePlayerStartLocation(Player(22), 22)
    SetPlayerColor(Player(22), ConvertPlayerColor(22))
    SetPlayerRacePreference(Player(22), RACE_PREF_RANDOM)
    SetPlayerRaceSelectable(Player(22), true)
    SetPlayerController(Player(22), MAP_CONTROL_USER)
end

function InitCustomTeams()
    SetPlayerTeam(Player(0), 0)
    SetPlayerTeam(Player(1), 0)
    SetPlayerTeam(Player(2), 0)
    SetPlayerTeam(Player(3), 0)
    SetPlayerTeam(Player(4), 0)
    SetPlayerTeam(Player(5), 0)
    SetPlayerTeam(Player(6), 0)
    SetPlayerTeam(Player(7), 0)
    SetPlayerTeam(Player(8), 0)
    SetPlayerTeam(Player(9), 0)
    SetPlayerTeam(Player(10), 0)
    SetPlayerTeam(Player(11), 0)
    SetPlayerTeam(Player(12), 0)
    SetPlayerTeam(Player(13), 0)
    SetPlayerTeam(Player(14), 0)
    SetPlayerTeam(Player(15), 0)
    SetPlayerTeam(Player(16), 0)
    SetPlayerTeam(Player(17), 0)
    SetPlayerTeam(Player(18), 0)
    SetPlayerTeam(Player(19), 0)
    SetPlayerTeam(Player(20), 0)
    SetPlayerTeam(Player(21), 0)
    SetPlayerTeam(Player(22), 0)
end

function InitAllyPriorities()
    SetStartLocPrioCount(0, 3)
    SetStartLocPrio(0, 0, 3, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(0, 1, 4, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(0, 2, 20, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(1, 4)
    SetStartLocPrio(1, 0, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 1, 13, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 2, 15, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 3, 16, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(2, 3)
    SetStartLocPrio(2, 0, 10, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(2, 1, 13, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 2, 19, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(3, 1)
    SetStartLocPrio(3, 0, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(4, 1)
    SetStartLocPrio(4, 0, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(5, 1)
    SetStartLocPrio(5, 0, 18, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(6, 1)
    SetStartLocPrio(6, 0, 17, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(7, 2)
    SetStartLocPrio(7, 0, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 1, 16, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(8, 2)
    SetStartLocPrio(8, 0, 21, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(8, 1, 22, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(9, 1)
    SetStartLocPrio(9, 0, 16, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(10, 3)
    SetStartLocPrio(10, 0, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(10, 1, 14, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(10, 2, 19, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(11, 3)
    SetStartLocPrio(11, 0, 5, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(11, 1, 12, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(11, 2, 18, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(12, 5)
    SetStartLocPrio(12, 0, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(12, 1, 11, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(12, 2, 17, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(12, 3, 21, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(12, 4, 22, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(13, 2)
    SetStartLocPrio(13, 0, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(13, 1, 19, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(14, 2)
    SetStartLocPrio(14, 0, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(14, 1, 19, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(15, 4)
    SetStartLocPrio(15, 0, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(15, 1, 7, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(15, 2, 9, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(15, 3, 16, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(16, 1)
    SetStartLocPrio(16, 0, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(17, 1)
    SetStartLocPrio(17, 0, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(18, 1)
    SetStartLocPrio(18, 0, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(19, 3)
    SetStartLocPrio(19, 0, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(19, 1, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(19, 2, 14, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(20, 3)
    SetStartLocPrio(20, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(20, 1, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(20, 2, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(21, 1)
    SetStartLocPrio(21, 0, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(22, 1)
    SetStartLocPrio(22, 0, 8, MAP_LOC_PRIO_HIGH)
end

function main()
    SetCameraBounds(-13696.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -15872.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 18816.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 16256.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -13696.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 16256.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 18816.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -15872.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
    SetDayNightModels("Environment\\DNC\\DNCAshenvale\\DNCAshenvaleTerrain\\DNCAshenvaleTerrain.mdl", "Environment\\DNC\\DNCAshenvale\\DNCAshenvaleUnit\\DNCAshenvaleUnit.mdl")
    SetTerrainFogEx(0, 100000.0, 100000.0, 0.000, 0.000, 0.000, 0.000)
    NewSoundEnvironment("Default")
    SetAmbientDaySound("AshenvaleDay")
    SetAmbientNightSound("AshenvaleNight")
    SetMapMusic("Music", true, 0)
    InitBlizzard()
    InitGlobals()
end

function config()
    SetMapName("")
    SetMapDescription("TRIGSTR_7297")
    SetPlayers(23)
    SetTeams(23)
    SetGamePlacement(MAP_PLACEMENT_TEAMS_TOGETHER)
    DefineStartLocation(0, -10368.0, 16000.0)
    DefineStartLocation(1, 6272.0, 8512.0)
    DefineStartLocation(2, 4160.0, 2944.0)
    DefineStartLocation(3, -8256.0, 9280.0)
    DefineStartLocation(4, -7424.0, 9408.0)
    DefineStartLocation(5, 4288.0, -5504.0)
    DefineStartLocation(6, -1792.0, 5440.0)
    DefineStartLocation(7, 4032.0, 11200.0)
    DefineStartLocation(8, -10112.0, 960.0)
    DefineStartLocation(9, 4224.0, 13312.0)
    DefineStartLocation(10, 4736.0, 192.0)
    DefineStartLocation(11, -3136.0, -9856.0)
    DefineStartLocation(12, -5376.0, -3648.0)
    DefineStartLocation(13, 4672.0, 5056.0)
    DefineStartLocation(14, 7680.0, 448.0)
    DefineStartLocation(15, 8512.0, 10944.0)
    DefineStartLocation(16, 4928.0, 12864.0)
    DefineStartLocation(17, -2368.0, 1600.0)
    DefineStartLocation(18, 4736.0, -9280.0)
    DefineStartLocation(19, 6080.0, 2304.0)
    DefineStartLocation(20, -12480.0, 10880.0)
    DefineStartLocation(21, -8512.0, 1408.0)
    DefineStartLocation(22, -10624.0, -896.0)
    InitCustomPlayerSlots()
    SetPlayerSlotAvailable(Player(0), MAP_CONTROL_USER)
    SetPlayerSlotAvailable(Player(1), MAP_CONTROL_USER)
    SetPlayerSlotAvailable(Player(2), MAP_CONTROL_USER)
    SetPlayerSlotAvailable(Player(3), MAP_CONTROL_USER)
    SetPlayerSlotAvailable(Player(4), MAP_CONTROL_USER)
    SetPlayerSlotAvailable(Player(5), MAP_CONTROL_USER)
    SetPlayerSlotAvailable(Player(6), MAP_CONTROL_USER)
    SetPlayerSlotAvailable(Player(7), MAP_CONTROL_USER)
    SetPlayerSlotAvailable(Player(8), MAP_CONTROL_USER)
    SetPlayerSlotAvailable(Player(9), MAP_CONTROL_USER)
    SetPlayerSlotAvailable(Player(10), MAP_CONTROL_USER)
    SetPlayerSlotAvailable(Player(11), MAP_CONTROL_USER)
    SetPlayerSlotAvailable(Player(12), MAP_CONTROL_USER)
    SetPlayerSlotAvailable(Player(13), MAP_CONTROL_USER)
    SetPlayerSlotAvailable(Player(14), MAP_CONTROL_USER)
    SetPlayerSlotAvailable(Player(15), MAP_CONTROL_USER)
    SetPlayerSlotAvailable(Player(16), MAP_CONTROL_USER)
    SetPlayerSlotAvailable(Player(17), MAP_CONTROL_USER)
    SetPlayerSlotAvailable(Player(18), MAP_CONTROL_USER)
    SetPlayerSlotAvailable(Player(19), MAP_CONTROL_USER)
    SetPlayerSlotAvailable(Player(20), MAP_CONTROL_USER)
    SetPlayerSlotAvailable(Player(21), MAP_CONTROL_USER)
    SetPlayerSlotAvailable(Player(22), MAP_CONTROL_USER)
    InitGenericPlayerSlots()
    InitAllyPriorities()
end

